name: Actions PR
on:
  pull_request:
    types: opened
    branches: main
jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Main
        run: echo "This is main branch"
  
    
